### ISSUE TITLE
Stock quote limit?

### ISSUE THREAD

**Issue by jcdocka** [dchrostowski/investopedia_simulator_api#25]
Is there a way to get around the 10 stock quote limit? Like if I want to get quotes on 100 stocks.

**Comment by dchrostowski** [comment]
I don't think there is a hard limit, but I believe there is some rate limiting involved so as not to overwhelm investopedia with stock quotes.

**Comment by jcdocka** [comment]
Thanks for the update! Would you happen to know about what it may be in a time period? Working on pinging some stock info and don't want to get turned off.

**Comment by dchrostowski** [comment]
I'm not too sure - but I think i set the rate limiting to about the edge of where Investopedia seemed to be rate limiting and causing errors.  There is a separate rate limit set for option chain lookups; that's going through a third party provider.
