### ISSUE TITLE
Get more info

### ISSUE THREAD

**Issue by jcdocka** [dchrostowski/investopedia_simulator_api#26]
I am looking at getting some more info for when I pull stock requests: specifically intraday Open, High, and Low price

In parsers.py I was able to find where you have some of the info: Line 110 

>     xpath_map = {
        'name': '//h3[@class="companyname"]/text()',
        'symbol': '//table[contains(@class,"table3")]/tbody/tr[1]/td[1]/h3[contains(@class,"pill")]/text()',
        'exchange': '//table[contains(@class,"table3")]//div[@class="marketname"]/text()',
        'last': '//table[@id="Table2"]/tbody/tr[1]/th[contains(text(),"Last")]/following-sibling::td/text()',
        'change': '//table[@id="Table2"]/tbody/tr[2]/th[contains(text(),"Change")]/following-sibling::td/text()',
        'change_percent': '//table[@id="Table2"]/tbody/tr[3]/th[contains(text(),"% Change")]/following-sibling::td/text()',
        'volume': '//table[@id="Table2"]/tbody/tr[4]/th[contains(text(),"Volume")]/following-sibling::td/text()'
    }

I was just wondering where you pull this information from so I could add my own hopefully. I also see that I will need to update api_models.py:

> class StockQuote(object):
    @coerce_method_params
    def __init__(
        self: object,
        symbol: str,
        name: str,
        exchange: str,
        last: Decimal,
        change: Decimal,
        change_percent: Decimal,
        volume: int

    ):
        self.symbol = symbol
        self.name = name
        self.last = last
        self.exchange = exchange
        self.change = change
        self.change_percent = change_percent
        self.volume = volume

Correct me if I'm wrong? Would there be anything else I would have to update?

**Comment by dchrostowski** [comment]
So yeah you're on the right track.  The stock quote data is pulled from the response of a POST request to /ajax/quotebox.aspx (see constants.py)

Here's an example response when I lookup GOOG:

```
    <table class="table3 panel">
        <tbody>
        <tr>
            <td class="txt moststock-name-td">
                <h3 class="pill ok">GOOG</h3>

            </td>
            <td class="txt">
                <div style="overflow: hidden;">
                    <h3 class="companyname">ALPHABET INC. CLASS C</h3>

                    <div class="marketname">(NASDAQ)</div>
                </div>
            </td>
            <td class="num">
                <h3 class="up inline">294.62</h3>
            </td>
        </tr>
        </tbody>
    </table>

            <table class="table2 order" id="Table2" runat="server">
            <tbody>
            <tr>
                <th>Last</th>
                <td class="num">1,827.0100</td>
            </tr>
            <tr>
                <th>Change</th>
                <td class="num up">294.62</td>
            </tr>
            <tr>
                <th>% Change</th>
                <td class="num up">19.23</td>
            </tr>
            <tr>
                <th>Volume</th>
                <td class="num">807,349</td>
            </tr>
                        <tr>
                <th>Day's High</th>
                <td class="num">1,835.0300</td>
            </tr>
            <tr>
                <th>Day's Low</th>
                <td class="num">1,789.4700</td>
            </tr>
                                    
            </tbody>
        </table>
```

The data returned is limited - I'm not seeing anything for **Open** but it looks like you could easily scrape the **Day's High** and **Day's Low** by adding these xpath expressions to `xpath_map` in parsers.py:

```
'days_high': '//table[@id="Table2"]/tbody/tr[5]/th[contains(text(),"Day\'s High")]/following-sibling::td/text()',
'days_low': '//table[@id="Table2"]/tbody/tr[6]/th[contains(text(),"Day\'s High")]/following-sibling::td/text()'
```

And yes, you're correct, you'd also have to modify the `StockQuote` class in api_models.py to handle the additional information:

```
class StockQuote(object):
    @coerce_method_params
    def __init__(
        self: object,
        symbol: str,
        name: str,
        exchange: str,
        last: Decimal,
        change: Decimal,
        change_percent: Decimal,
        volume: int,
        days_high: Decimal,
        days_low: Decimal

    ):
        self.symbol = symbol
        self.name = name
        self.last = last
        self.exchange = exchange
        self.change = change
        self.change_percent = change_percent
        self.volume = volume
        self.days_high = days_high
        self.days_low = days_low
```

These changes are actually pretty easy so I'm going to test and commit them to master.  

As for getting the open price, I'll look into seeing if I can maybe scrape an additional resource on Investopedia's end that offers a bit more information than what's available when making a request to /ajax/quotebox.aspx

**Comment by dchrostowski** [comment]
actually, now that I think about it, the open price could be calculated by subtracting `change` from `last`.

```self.open = self.last - self.change```

I'll add that into the commit as well.

**Comment by jcdocka** [comment]
All looks great! Thanks! I wasn't sure what was available and the syntax

**Comment by dchrostowski** [comment]
Merged in the changes.  Here's how to get the open, high, and low:

```
quote = client.get_stock_quote('GOOG')
print(quote.days_high)
print(quote.days_low)
print(quote.open)
```
